### PR TITLE
Add RSS comment only if rss is activated

### PR DESCRIPTION
**Pull request by andygrunwald**

### CODE REVIEW

**Comment by andygrunwald** [comment]
Side note: I maintain an active fork of this repository.
The reason for this fork is that it seems to be silent about this repository.
See https://github.com/andygrunwald/hugo-type-theme#this-is-a-fork for more information.

This PR was applied to this fork.

**Comment by andygrunwald** [comment]
@digitalcraftsman Any new on this?

**Comment by keyphact** [comment]
> Side note: I maintain an active fork of this repository.
> The reason for this fork is that it seems to be silent about this repository.
> See https://github.com/andygrunwald/hugo-type-theme#this-is-a-fork for more information.
> 
> This PR was applied to this fork.

Maybe not the best place to discuss can you list out the differences between yours and @digitalcraftsman 's repos, so I can make a choice of which to use.

Thanks

**Comment by andygrunwald** [comment]
@keyphact In general i "only" applied bugfixes that are available as a PR here. In every PR that i have applied, i wrote a comment. See https://github.com/digitalcraftsman/hugo-type-theme/pull/30#issuecomment-375964382

The compare view shows this quite good: https://github.com/digitalcraftsman/hugo-type-theme/compare/master...andygrunwald:develop

**Comment by keyphact** [comment]
Great stuff, thanks @andygrunwald .

**Comment by digitalcraftsman** [comment]
Thanks for you work Andy. I've merged this PR in https://github.com/digitalcraftsman/hugo-type-theme/commit/417c0b33423c6ff734d65356e391220535028120.

**Pull request closed without merging**
